services:
  psylodb:
    image: postgres:17.1
    container_name: psylodb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - psylo-network

  psylomlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psylomlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
    labels:
      - "dev.orbstack.http-port=5000"
    depends_on:
      psylodb:
        condition: service_healthy
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psylodb:5432/${POSTGRES_DB}
      --default-artifact-root file:///mlflow/artifacts
      --host 0.0.0.0
    restart: unless-stopped
    networks:
      - psylo-network

volumes:
  pgdata:

networks:
  psylo-network:
    driver: bridge
