services:
  postgres:
    image: postgres:latest
    container_name: psylo_postgres
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow:
    image: psylo-mlflow:2.22.0
    container_name: psylo_mlflow
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
    command: [
      "mlflow", "server",
      "--backend-store-uri", "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}",
      "--default-artifact-root", "/mlflow/artifacts",
      "--host", "0.0.0.0",
      "--port", "5000"
    ]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
